In [54]:
import numpy as np
import scipy as sc

In [55]:
# 円環型都市空間の設定

# 都市数(2^n個)
scale = 2
size = 2**scale
# 輸送抵抗
phi = 0.5
# 円環行列
up = np.logspace(start=0,stop=int(size/2-1),num=int(0+size/2),base=phi)
down = np.logspace(start=int(size/2),stop=1,num=int(0+size/2),base=phi)
arr = np.concatenate([up,down])
proximity = sc.linalg.circulant(arr)
distance = 1/np.sum(arr)*proximity
# 対象均衡
dist_0 = np.full(size,1/size)

In [56]:
distance

array([[0.44444444, 0.22222222, 0.11111111, 0.22222222],
       [0.22222222, 0.44444444, 0.22222222, 0.11111111],
       [0.11111111, 0.22222222, 0.44444444, 0.22222222],
       [0.22222222, 0.11111111, 0.22222222, 0.44444444]])

In [116]:
alpha = 1
theta = 0.5
beta = 0.

# 円環行列
up = np.logspace(start=0,stop=int(size/2-1),num=int(0+size/2),base=theta)
down = np.logspace(start=int(size/2),stop=1,num=int(0+size/2),base=theta)
arr = np.concatenate([up,down])

a = np.array([
    [1-beta,1,1,1],
    [1,0-beta,-1,0],
    [1,-1,1-beta,-1],
    [1,0,-1,0-beta]
])

In [122]:
(1-0.5)/(1+0.5)

0.3333333333333333

In [123]:
(1-0.5**0.5)/(1+0.5**0.5)

0.17157287525380988

In [119]:
(1-beta)**(1/2)

0.7071067811865476

In [118]:
(1-theta)/(1+theta)*alpha

0.3333333333333333

In [120]:
1/np.sum(arr)*np.dot(a,arr)

array([0.77777778, 0.22222222, 0.05555556, 0.22222222])

In [62]:
arr

array([1.  , 0.5 , 0.25, 0.5 ])

In [10]:
np.logspace(start=0,stop=3,num=(0+3+1),base=10)

array([   1.,   10.,  100., 1000.])